### ISSUE TITLE
Document Configuration

### ISSUE THREAD

**Issue by Naheel-Azawy** [OpenCovidTrace/oextrace-android#2]
Based on the [README](https://github.com/OpenCovidTrace/ContactTracing), [this](https://github.com/OpenCovidTrace/oct-storage) storage server backend can be used.

I did manage to deploy the server. But now, how to connect the client apps (both android and ios, but let's focus on android for now) to work with my server?

Also, the project would be much easier to work with if more documentation was provided.

And thank you all for you great efforts!

**Comment by alexnivanov** [comment]
@Naheel-Azawy see API_HOST variable in https://github.com/OpenCovidTrace/oextrace-android/blob/master/app/build.gradle and its usage through the code.
We know that our documentation is poor, but Apple/Google totally blocked our app, so we don't have resources allocated for this project at the moment :(

**Comment by Naheel-Azawy** [comment]
@alexnivanov Wow... well, first and most significantly, why did they block it?

For the API_HOST, I did find it already. For now I'm testing with docker on my machine, so the server's address is my private IP, say, 192.168.0.123 and port 8000 as set by default. So, I set my API_HOST to "192.168.0.123:8000".

Now if I record contact, the URL in the QR code is something like "https://contact.192.168.0.123:8000/app/contact..." which cannot be reached by the client. I tried replacing with http and removing "contact" to be like "http://192.168.0.123:8000/app/contact...", this time I got "Error: Requested URL /app/contact not found".

I guess I should dig further to understand the server interface, but it would be much better and easier if you can help.

I've seen multiple exposure notification implementations, this one is the best I've seen so far. It's a shame it has been blocked. It would've been very nice if it was only documented properly.

**Comment by alexnivanov** [comment]
@Naheel-Azawy They only allow covid related apps in the stores for official medical/government organizations.

Regarding the contacts: it’s another backend service: https://github.com/OpenCovidTrace/oct-contact

**Comment by Naheel-Azawy** [comment]
@alexnivanov thanks! I'll try experimenting with that oct-contact. I hope this project get some more interest and gets documented someday.

**Comment by alexnivanov** [comment]
@Naheel-Azawy welcome and good luck with that!
